/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VigyanKendraDetailsRequestDto } from '../../models/vigyan-kendra-details-request-dto';

export interface GetAllVigyanKendras$Params {
}

export function getAllVigyanKendras(http: HttpClient, rootUrl: string, params?: GetAllVigyanKendras$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllVigyanKendras.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>;
    })
  );
}

getAllVigyanKendras.PATH = '/api/vigyan-kendra';
