/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SchoolDetailsResponseDto } from '../../models/school-details-response-dto';

export interface GetSchoolsByCode$Params {
  id: number;
}

export function getSchoolsByCode(http: HttpClient, rootUrl: string, params: GetSchoolsByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolDetailsResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getSchoolsByCode.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SchoolDetailsResponseDto>>;
    })
  );
}

getSchoolsByCode.PATH = '/api/vigyan-kendra/schools/{id}';
