/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VigyanKendraDetailsRequestDto } from '../../models/vigyan-kendra-details-request-dto';

export interface GetVigyanKendraById$Params {
  id: number;
}

export function getVigyanKendraById(http: HttpClient, rootUrl: string, params: GetVigyanKendraById$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
  const rb = new RequestBuilder(rootUrl, getVigyanKendraById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VigyanKendraDetailsRequestDto>;
    })
  );
}

getVigyanKendraById.PATH = '/api/vigyan-kendra/{id}';
