/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VigyanKendraDetailsRequestDto } from '../../models/vigyan-kendra-details-request-dto';

export interface GetByCode$Params {
  code: string;
}

export function getByCode(http: HttpClient, rootUrl: string, params: GetByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
  const rb = new RequestBuilder(rootUrl, getByCode.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VigyanKendraDetailsRequestDto>;
    })
  );
}

getByCode.PATH = '/api/vigyan-kendra/code/{code}';
