/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VigyanKendraDetailsRequestDto } from '../../models/vigyan-kendra-details-request-dto';

export interface UpdateVigyanKendraDetails$Params {
      body: VigyanKendraDetailsRequestDto
}

export function updateVigyanKendraDetails(http: HttpClient, rootUrl: string, params: UpdateVigyanKendraDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
  const rb = new RequestBuilder(rootUrl, updateVigyanKendraDetails.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VigyanKendraDetailsRequestDto>;
    })
  );
}

updateVigyanKendraDetails.PATH = '/api/vigyan-kendra';
