/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollmentReportingResponse } from '../../models/enrollment-reporting-response';

export interface GetAllReports$Params {
}

export function getAllReports(http: HttpClient, rootUrl: string, params?: GetAllReports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EnrollmentReportingResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllReports.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EnrollmentReportingResponse>>;
    })
  );
}

getAllReports.PATH = '/api/reporting/enrollment';
