/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollmentReportingRequest } from '../../models/enrollment-reporting-request';
import { EnrollmentReportingResponse } from '../../models/enrollment-reporting-response';

export interface PrepareStatisticsReport$Params {
      body: EnrollmentReportingRequest
}

export function prepareStatisticsReport(http: HttpClient, rootUrl: string, params: PrepareStatisticsReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentReportingResponse>> {
  const rb = new RequestBuilder(rootUrl, prepareStatisticsReport.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnrollmentReportingResponse>;
    })
  );
}

prepareStatisticsReport.PATH = '/api/reporting/statistics';
