/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubjectDetailsRequestDto } from '../../models/subject-details-request-dto';
import { SubjectDetailsResponseDto } from '../../models/subject-details-response-dto';

export interface CreateSubject$Params {
      body: SubjectDetailsRequestDto
}

export function createSubject(http: HttpClient, rootUrl: string, params: CreateSubject$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createSubject.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubjectDetailsResponseDto>;
    })
  );
}

createSubject.PATH = '/api/subject-details';
