/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubjectDetailsResponseDto } from '../../models/subject-details-response-dto';

export interface GetSubjectById$Params {
  id: number;
}

export function getSubjectById(http: HttpClient, rootUrl: string, params: GetSubjectById$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getSubjectById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubjectDetailsResponseDto>;
    })
  );
}

getSubjectById.PATH = '/api/subject-details/{id}';
