/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentMarksRequestDto } from '../../models/student-marks-request-dto';

export interface CreateMarks$Params {
      body: StudentMarksRequestDto
}

export function createMarks(http: HttpClient, rootUrl: string, params: CreateMarks$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
  const rb = new RequestBuilder(rootUrl, createMarks.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentMarksRequestDto>;
    })
  );
}

createMarks.PATH = '/api/student-marks';
