/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentMarksRequestDto } from '../../models/student-marks-request-dto';

export interface GetMarksById$Params {

/**
 * ID of the StudentMarks record to retrieve
 */
  id: number;
}

export function getMarksById(http: HttpClient, rootUrl: string, params: GetMarksById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
  const rb = new RequestBuilder(rootUrl, getMarksById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentMarksRequestDto>;
    })
  );
}

getMarksById.PATH = '/api/student-marks/{id}';
