/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentRequestDto } from '../../models/student-request-dto';
import { StudentResponseDto } from '../../models/student-response-dto';

export interface CreateStudent$Params {
      body: StudentRequestDto
}

export function createStudent(http: HttpClient, rootUrl: string, params: CreateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createStudent.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentResponseDto>;
    })
  );
}

createStudent.PATH = '/api/students';
