/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RollNumberAssignmentStatus } from '../../models/roll-number-assignment-status';

export interface GetRollNumberAssignmentStatus$Params {
  vigyanKendraId: number;
}

export function getRollNumberAssignmentStatus(http: HttpClient, rootUrl: string, params: GetRollNumberAssignmentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<RollNumberAssignmentStatus>> {
  const rb = new RequestBuilder(rootUrl, getRollNumberAssignmentStatus.PATH, 'get');
  if (params) {
    rb.path('vigyanKendraId', params.vigyanKendraId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RollNumberAssignmentStatus>;
    })
  );
}

getRollNumberAssignmentStatus.PATH = '/api/students/roll-number-assignment-status/{vigyanKendraId}';
