/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentResponseDto } from '../../models/student-response-dto';

export interface GetStudentById$Params {
  id: number;
}

export function getStudentById(http: HttpClient, rootUrl: string, params: GetStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getStudentById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentResponseDto>;
    })
  );
}

getStudentById.PATH = '/api/students/{id}';
