/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEnrollmentSession } from '../fn/enrollment-session-management-api/create-enrollment-session';
import { CreateEnrollmentSession$Params } from '../fn/enrollment-session-management-api/create-enrollment-session';
import { deleteEnrollmentSessionById } from '../fn/enrollment-session-management-api/delete-enrollment-session-by-id';
import { DeleteEnrollmentSessionById$Params } from '../fn/enrollment-session-management-api/delete-enrollment-session-by-id';
import { EnrollmentSession } from '../models/enrollment-session';
import { getAllEnrollmentSession } from '../fn/enrollment-session-management-api/get-all-enrollment-session';
import { GetAllEnrollmentSession$Params } from '../fn/enrollment-session-management-api/get-all-enrollment-session';
import { getEnrollmentSessionById } from '../fn/enrollment-session-management-api/get-enrollment-session-by-id';
import { GetEnrollmentSessionById$Params } from '../fn/enrollment-session-management-api/get-enrollment-session-by-id';
import { setEnrollmentFreezed } from '../fn/enrollment-session-management-api/set-enrollment-freezed';
import { SetEnrollmentFreezed$Params } from '../fn/enrollment-session-management-api/set-enrollment-freezed';
import { setEnrollmentSessionAsActive } from '../fn/enrollment-session-management-api/set-enrollment-session-as-active';
import { SetEnrollmentSessionAsActive$Params } from '../fn/enrollment-session-management-api/set-enrollment-session-as-active';
import { setEnrollmentSessionAsInActive } from '../fn/enrollment-session-management-api/set-enrollment-session-as-in-active';
import { SetEnrollmentSessionAsInActive$Params } from '../fn/enrollment-session-management-api/set-enrollment-session-as-in-active';
import { setEnrollmentUnFreezed } from '../fn/enrollment-session-management-api/set-enrollment-un-freezed';
import { SetEnrollmentUnFreezed$Params } from '../fn/enrollment-session-management-api/set-enrollment-un-freezed';
import { setModificationFreezed } from '../fn/enrollment-session-management-api/set-modification-freezed';
import { SetModificationFreezed$Params } from '../fn/enrollment-session-management-api/set-modification-freezed';
import { setModificationUnFreezed } from '../fn/enrollment-session-management-api/set-modification-un-freezed';
import { SetModificationUnFreezed$Params } from '../fn/enrollment-session-management-api/set-modification-un-freezed';
import { updateEnrollmentSession } from '../fn/enrollment-session-management-api/update-enrollment-session';
import { UpdateEnrollmentSession$Params } from '../fn/enrollment-session-management-api/update-enrollment-session';

@Injectable({ providedIn: 'root' })
export class EnrollmentSessionManagementApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllEnrollmentSession()` */
  static readonly GetAllEnrollmentSessionPath = '/api/enrollment-session';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllEnrollmentSession()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEnrollmentSession$Response(params?: GetAllEnrollmentSession$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EnrollmentSession>>> {
    return getAllEnrollmentSession(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllEnrollmentSession$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEnrollmentSession(params?: GetAllEnrollmentSession$Params, context?: HttpContext): Observable<Array<EnrollmentSession>> {
    return this.getAllEnrollmentSession$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EnrollmentSession>>): Array<EnrollmentSession> => r.body)
    );
  }

  /** Path part for operation `updateEnrollmentSession()` */
  static readonly UpdateEnrollmentSessionPath = '/api/enrollment-session';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEnrollmentSession()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEnrollmentSession$Response(params: UpdateEnrollmentSession$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return updateEnrollmentSession(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEnrollmentSession$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEnrollmentSession(params: UpdateEnrollmentSession$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.updateEnrollmentSession$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `createEnrollmentSession()` */
  static readonly CreateEnrollmentSessionPath = '/api/enrollment-session';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEnrollmentSession()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEnrollmentSession$Response(params: CreateEnrollmentSession$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return createEnrollmentSession(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEnrollmentSession$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEnrollmentSession(params: CreateEnrollmentSession$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.createEnrollmentSession$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `getEnrollmentSessionById()` */
  static readonly GetEnrollmentSessionByIdPath = '/api/enrollment-session/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEnrollmentSessionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEnrollmentSessionById$Response(params: GetEnrollmentSessionById$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return getEnrollmentSessionById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEnrollmentSessionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEnrollmentSessionById(params: GetEnrollmentSessionById$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.getEnrollmentSessionById$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `deleteEnrollmentSessionById()` */
  static readonly DeleteEnrollmentSessionByIdPath = '/api/enrollment-session/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEnrollmentSessionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEnrollmentSessionById$Response(params: DeleteEnrollmentSessionById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEnrollmentSessionById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEnrollmentSessionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEnrollmentSessionById(params: DeleteEnrollmentSessionById$Params, context?: HttpContext): Observable<void> {
    return this.deleteEnrollmentSessionById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setEnrollmentUnFreezed()` */
  static readonly SetEnrollmentUnFreezedPath = '/api/enrollment-session/{id}/unfreeze';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setEnrollmentUnFreezed()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentUnFreezed$Response(params: SetEnrollmentUnFreezed$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setEnrollmentUnFreezed(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setEnrollmentUnFreezed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentUnFreezed(params: SetEnrollmentUnFreezed$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setEnrollmentUnFreezed$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `setModificationUnFreezed()` */
  static readonly SetModificationUnFreezedPath = '/api/enrollment-session/{id}/modification-unfreeze';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setModificationUnFreezed()` instead.
   *
   * This method doesn't expect any request body.
   */
  setModificationUnFreezed$Response(params: SetModificationUnFreezed$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setModificationUnFreezed(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setModificationUnFreezed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setModificationUnFreezed(params: SetModificationUnFreezed$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setModificationUnFreezed$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `setModificationFreezed()` */
  static readonly SetModificationFreezedPath = '/api/enrollment-session/{id}/modification-freeze';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setModificationFreezed()` instead.
   *
   * This method doesn't expect any request body.
   */
  setModificationFreezed$Response(params: SetModificationFreezed$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setModificationFreezed(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setModificationFreezed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setModificationFreezed(params: SetModificationFreezed$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setModificationFreezed$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `setEnrollmentSessionAsInActive()` */
  static readonly SetEnrollmentSessionAsInActivePath = '/api/enrollment-session/{id}/inactive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setEnrollmentSessionAsInActive()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentSessionAsInActive$Response(params: SetEnrollmentSessionAsInActive$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setEnrollmentSessionAsInActive(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setEnrollmentSessionAsInActive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentSessionAsInActive(params: SetEnrollmentSessionAsInActive$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setEnrollmentSessionAsInActive$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `setEnrollmentFreezed()` */
  static readonly SetEnrollmentFreezedPath = '/api/enrollment-session/{id}/freeze';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setEnrollmentFreezed()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentFreezed$Response(params: SetEnrollmentFreezed$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setEnrollmentFreezed(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setEnrollmentFreezed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentFreezed(params: SetEnrollmentFreezed$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setEnrollmentFreezed$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

  /** Path part for operation `setEnrollmentSessionAsActive()` */
  static readonly SetEnrollmentSessionAsActivePath = '/api/enrollment-session/{id}/active';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setEnrollmentSessionAsActive()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentSessionAsActive$Response(params: SetEnrollmentSessionAsActive$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
    return setEnrollmentSessionAsActive(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setEnrollmentSessionAsActive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setEnrollmentSessionAsActive(params: SetEnrollmentSessionAsActive$Params, context?: HttpContext): Observable<EnrollmentSession> {
    return this.setEnrollmentSessionAsActive$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentSession>): EnrollmentSession => r.body)
    );
  }

}
