/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignSchool } from '../fn/examination-centre-details-api/assign-school';
import { AssignSchool$Params } from '../fn/examination-centre-details-api/assign-school';
import { createExamCenter } from '../fn/examination-centre-details-api/create-exam-center';
import { CreateExamCenter$Params } from '../fn/examination-centre-details-api/create-exam-center';
import { deAssignSchool } from '../fn/examination-centre-details-api/de-assign-school';
import { DeAssignSchool$Params } from '../fn/examination-centre-details-api/de-assign-school';
import { deleteExamCenter } from '../fn/examination-centre-details-api/delete-exam-center';
import { DeleteExamCenter$Params } from '../fn/examination-centre-details-api/delete-exam-center';
import { ExaminationCentreDetailsRequestDto } from '../models/examination-centre-details-request-dto';
import { getAllExamCenters } from '../fn/examination-centre-details-api/get-all-exam-centers';
import { GetAllExamCenters$Params } from '../fn/examination-centre-details-api/get-all-exam-centers';
import { getAllExamCentersByVigyanKendraId } from '../fn/examination-centre-details-api/get-all-exam-centers-by-vigyan-kendra-id';
import { GetAllExamCentersByVigyanKendraId$Params } from '../fn/examination-centre-details-api/get-all-exam-centers-by-vigyan-kendra-id';
import { getExamCenterById } from '../fn/examination-centre-details-api/get-exam-center-by-id';
import { GetExamCenterById$Params } from '../fn/examination-centre-details-api/get-exam-center-by-id';
import { updateExamCenter } from '../fn/examination-centre-details-api/update-exam-center';
import { UpdateExamCenter$Params } from '../fn/examination-centre-details-api/update-exam-center';

@Injectable({ providedIn: 'root' })
export class ExaminationCentreDetailsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllExamCenters()` */
  static readonly GetAllExamCentersPath = '/api/examination-centres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllExamCenters()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExamCenters$Response(params?: GetAllExamCenters$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>> {
    return getAllExamCenters(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllExamCenters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExamCenters(params?: GetAllExamCenters$Params, context?: HttpContext): Observable<Array<ExaminationCentreDetailsRequestDto>> {
    return this.getAllExamCenters$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>): Array<ExaminationCentreDetailsRequestDto> => r.body)
    );
  }

  /** Path part for operation `updateExamCenter()` */
  static readonly UpdateExamCenterPath = '/api/examination-centres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExamCenter()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExamCenter$Response(params: UpdateExamCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return updateExamCenter(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExamCenter$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExamCenter(params: UpdateExamCenter$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.updateExamCenter$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `createExamCenter()` */
  static readonly CreateExamCenterPath = '/api/examination-centres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createExamCenter()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createExamCenter$Response(params: CreateExamCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return createExamCenter(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createExamCenter$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createExamCenter(params: CreateExamCenter$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.createExamCenter$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `deAssignSchool()` */
  static readonly DeAssignSchoolPath = '/api/examination-centres/de-assign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deAssignSchool()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deAssignSchool$Response(params: DeAssignSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return deAssignSchool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deAssignSchool$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deAssignSchool(params: DeAssignSchool$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.deAssignSchool$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `assignSchool()` */
  static readonly AssignSchoolPath = '/api/examination-centres/assign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignSchool()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignSchool$Response(params: AssignSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return assignSchool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignSchool$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignSchool(params: AssignSchool$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.assignSchool$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `getExamCenterById()` */
  static readonly GetExamCenterByIdPath = '/api/examination-centres/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getExamCenterById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExamCenterById$Response(params: GetExamCenterById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return getExamCenterById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getExamCenterById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExamCenterById(params: GetExamCenterById$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.getExamCenterById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `deleteExamCenter()` */
  static readonly DeleteExamCenterPath = '/api/examination-centres/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteExamCenter()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExamCenter$Response(params: DeleteExamCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteExamCenter(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteExamCenter$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExamCenter(params: DeleteExamCenter$Params, context?: HttpContext): Observable<void> {
    return this.deleteExamCenter$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllExamCentersByVigyanKendraId()` */
  static readonly GetAllExamCentersByVigyanKendraIdPath = '/api/examination-centres/vigyan-kendra/{vigyanKendraId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllExamCentersByVigyanKendraId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExamCentersByVigyanKendraId$Response(params: GetAllExamCentersByVigyanKendraId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>> {
    return getAllExamCentersByVigyanKendraId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllExamCentersByVigyanKendraId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllExamCentersByVigyanKendraId(params: GetAllExamCentersByVigyanKendraId$Params, context?: HttpContext): Observable<Array<ExaminationCentreDetailsRequestDto>> {
    return this.getAllExamCentersByVigyanKendraId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>): Array<ExaminationCentreDetailsRequestDto> => r.body)
    );
  }

}
