/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create3 } from '../fn/examination-centre-details-api/create-3';
import { Create3$Params } from '../fn/examination-centre-details-api/create-3';
import { delete$ } from '../fn/examination-centre-details-api/delete';
import { Delete$Params } from '../fn/examination-centre-details-api/delete';
import { ExaminationCentreDetailsRequestDto } from '../models/examination-centre-details-request-dto';
import { getAll4 } from '../fn/examination-centre-details-api/get-all-4';
import { GetAll4$Params } from '../fn/examination-centre-details-api/get-all-4';
import { getById } from '../fn/examination-centre-details-api/get-by-id';
import { GetById$Params } from '../fn/examination-centre-details-api/get-by-id';
import { update2 } from '../fn/examination-centre-details-api/update-2';
import { Update2$Params } from '../fn/examination-centre-details-api/update-2';

@Injectable({ providedIn: 'root' })
export class ExaminationCentreDetailsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/api/examination-centres/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `update2()` */
  static readonly Update2Path = '/api/examination-centres/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2$Response(params: Update2$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return update2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2(params: Update2$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.update2$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/examination-centres/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAll4()` */
  static readonly GetAll4Path = '/api/examination-centres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll4()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll4$Response(params?: GetAll4$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>> {
    return getAll4(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll4$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll4(params?: GetAll4$Params, context?: HttpContext): Observable<Array<ExaminationCentreDetailsRequestDto>> {
    return this.getAll4$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>): Array<ExaminationCentreDetailsRequestDto> => r.body)
    );
  }

  /** Path part for operation `create3()` */
  static readonly Create3Path = '/api/examination-centres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create3()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create3$Response(params: Create3$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
    return create3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create3$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create3(params: Create3$Params, context?: HttpContext): Observable<ExaminationCentreDetailsRequestDto> {
    return this.create3$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExaminationCentreDetailsRequestDto>): ExaminationCentreDetailsRequestDto => r.body)
    );
  }

}
