/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteReport } from '../fn/reporting-api/delete-report';
import { DeleteReport$Params } from '../fn/reporting-api/delete-report';
import { downloadExcel } from '../fn/reporting-api/download-excel';
import { DownloadExcel$Params } from '../fn/reporting-api/download-excel';
import { EnrollmentReportingResponse } from '../models/enrollment-reporting-response';
import { getAllReports } from '../fn/reporting-api/get-all-reports';
import { GetAllReports$Params } from '../fn/reporting-api/get-all-reports';
import { prepareReport } from '../fn/reporting-api/prepare-report';
import { PrepareReport$Params } from '../fn/reporting-api/prepare-report';
import { prepareStatisticsReport } from '../fn/reporting-api/prepare-statistics-report';
import { PrepareStatisticsReport$Params } from '../fn/reporting-api/prepare-statistics-report';

@Injectable({ providedIn: 'root' })
export class ReportingApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `prepareStatisticsReport()` */
  static readonly PrepareStatisticsReportPath = '/api/reporting/statistics';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `prepareStatisticsReport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  prepareStatisticsReport$Response(params: PrepareStatisticsReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentReportingResponse>> {
    return prepareStatisticsReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `prepareStatisticsReport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  prepareStatisticsReport(params: PrepareStatisticsReport$Params, context?: HttpContext): Observable<EnrollmentReportingResponse> {
    return this.prepareStatisticsReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentReportingResponse>): EnrollmentReportingResponse => r.body)
    );
  }

  /** Path part for operation `getAllReports()` */
  static readonly GetAllReportsPath = '/api/reporting/enrollment';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReports$Response(params?: GetAllReports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EnrollmentReportingResponse>>> {
    return getAllReports(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReports(params?: GetAllReports$Params, context?: HttpContext): Observable<Array<EnrollmentReportingResponse>> {
    return this.getAllReports$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EnrollmentReportingResponse>>): Array<EnrollmentReportingResponse> => r.body)
    );
  }

  /** Path part for operation `prepareReport()` */
  static readonly PrepareReportPath = '/api/reporting/enrollment';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `prepareReport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  prepareReport$Response(params: PrepareReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentReportingResponse>> {
    return prepareReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `prepareReport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  prepareReport(params: PrepareReport$Params, context?: HttpContext): Observable<EnrollmentReportingResponse> {
    return this.prepareReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnrollmentReportingResponse>): EnrollmentReportingResponse => r.body)
    );
  }

  /** Path part for operation `downloadExcel()` */
  static readonly DownloadExcelPath = '/api/reporting/download/{vigyanKendraCode}/{key}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadExcel()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadExcel$Response(params: DownloadExcel$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return downloadExcel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadExcel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadExcel(params: DownloadExcel$Params, context?: HttpContext): Observable<string> {
    return this.downloadExcel$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `deleteReport()` */
  static readonly DeleteReportPath = '/api/reporting/enrollment/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport$Response(params: DeleteReport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport(params: DeleteReport$Params, context?: HttpContext): Observable<void> {
    return this.deleteReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
