/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSchool } from '../fn/school-details-api/create-school';
import { CreateSchool$Params } from '../fn/school-details-api/create-school';
import { deleteSchool } from '../fn/school-details-api/delete-school';
import { DeleteSchool$Params } from '../fn/school-details-api/delete-school';
import { getAllSchools } from '../fn/school-details-api/get-all-schools';
import { GetAllSchools$Params } from '../fn/school-details-api/get-all-schools';
import { getSchoolById } from '../fn/school-details-api/get-school-by-id';
import { GetSchoolById$Params } from '../fn/school-details-api/get-school-by-id';
import { removeExamCenter } from '../fn/school-details-api/remove-exam-center';
import { RemoveExamCenter$Params } from '../fn/school-details-api/remove-exam-center';
import { SchoolDetailsResponseDto } from '../models/school-details-response-dto';
import { updateSchool } from '../fn/school-details-api/update-school';
import { UpdateSchool$Params } from '../fn/school-details-api/update-school';

@Injectable({ providedIn: 'root' })
export class SchoolDetailsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllSchools()` */
  static readonly GetAllSchoolsPath = '/api/schools';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSchools()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSchools$Response(params?: GetAllSchools$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolDetailsResponseDto>>> {
    return getAllSchools(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSchools$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSchools(params?: GetAllSchools$Params, context?: HttpContext): Observable<Array<SchoolDetailsResponseDto>> {
    return this.getAllSchools$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SchoolDetailsResponseDto>>): Array<SchoolDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `updateSchool()` */
  static readonly UpdateSchoolPath = '/api/schools';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSchool()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSchool$Response(params: UpdateSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<SchoolDetailsResponseDto>> {
    return updateSchool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSchool$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSchool(params: UpdateSchool$Params, context?: HttpContext): Observable<SchoolDetailsResponseDto> {
    return this.updateSchool$Response(params, context).pipe(
      map((r: StrictHttpResponse<SchoolDetailsResponseDto>): SchoolDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `createSchool()` */
  static readonly CreateSchoolPath = '/api/schools';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSchool()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSchool$Response(params: CreateSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<SchoolDetailsResponseDto>> {
    return createSchool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSchool$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSchool(params: CreateSchool$Params, context?: HttpContext): Observable<SchoolDetailsResponseDto> {
    return this.createSchool$Response(params, context).pipe(
      map((r: StrictHttpResponse<SchoolDetailsResponseDto>): SchoolDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteSchool()` */
  static readonly DeleteSchoolPath = '/api/schools';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSchool()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSchool$Response(params: DeleteSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSchool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSchool$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSchool(params: DeleteSchool$Params, context?: HttpContext): Observable<void> {
    return this.deleteSchool$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSchoolById()` */
  static readonly GetSchoolByIdPath = '/api/schools/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSchoolById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolById$Response(params: GetSchoolById$Params, context?: HttpContext): Observable<StrictHttpResponse<SchoolDetailsResponseDto>> {
    return getSchoolById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSchoolById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolById(params: GetSchoolById$Params, context?: HttpContext): Observable<SchoolDetailsResponseDto> {
    return this.getSchoolById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SchoolDetailsResponseDto>): SchoolDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `removeExamCenter()` */
  static readonly RemoveExamCenterPath = '/api/schools/remove-exam-center/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeExamCenter()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeExamCenter$Response(params: RemoveExamCenter$Params, context?: HttpContext): Observable<StrictHttpResponse<SchoolDetailsResponseDto>> {
    return removeExamCenter(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeExamCenter$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeExamCenter(params: RemoveExamCenter$Params, context?: HttpContext): Observable<SchoolDetailsResponseDto> {
    return this.removeExamCenter$Response(params, context).pipe(
      map((r: StrictHttpResponse<SchoolDetailsResponseDto>): SchoolDetailsResponseDto => r.body)
    );
  }

}
