/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createStudent } from '../fn/student-enrollment-api/create-student';
import { CreateStudent$Params } from '../fn/student-enrollment-api/create-student';
import { deleteStudent } from '../fn/student-enrollment-api/delete-student';
import { DeleteStudent$Params } from '../fn/student-enrollment-api/delete-student';
import { generateDummyData } from '../fn/student-enrollment-api/generate-dummy-data';
import { GenerateDummyData$Params } from '../fn/student-enrollment-api/generate-dummy-data';
import { getAllStudents } from '../fn/student-enrollment-api/get-all-students';
import { GetAllStudents$Params } from '../fn/student-enrollment-api/get-all-students';
import { getAllStudentsByVigyanKendraId } from '../fn/student-enrollment-api/get-all-students-by-vigyan-kendra-id';
import { GetAllStudentsByVigyanKendraId$Params } from '../fn/student-enrollment-api/get-all-students-by-vigyan-kendra-id';
import { getStudentById } from '../fn/student-enrollment-api/get-student-by-id';
import { GetStudentById$Params } from '../fn/student-enrollment-api/get-student-by-id';
import { StudentResponseDto } from '../models/student-response-dto';
import { updateStudent } from '../fn/student-enrollment-api/update-student';
import { UpdateStudent$Params } from '../fn/student-enrollment-api/update-student';

@Injectable({ providedIn: 'root' })
export class StudentEnrollmentApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllStudents()` */
  static readonly GetAllStudentsPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStudents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents$Response(params?: GetAllStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponseDto>>> {
    return getAllStudents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStudents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents(params?: GetAllStudents$Params, context?: HttpContext): Observable<Array<StudentResponseDto>> {
    return this.getAllStudents$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponseDto>>): Array<StudentResponseDto> => r.body)
    );
  }

  /** Path part for operation `updateStudent()` */
  static readonly UpdateStudentPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent$Response(params: UpdateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return updateStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent(params: UpdateStudent$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.updateStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `createStudent()` */
  static readonly CreateStudentPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStudent$Response(params: CreateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return createStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStudent(params: CreateStudent$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.createStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `getStudentById()` */
  static readonly GetStudentByIdPath = '/api/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStudentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById$Response(params: GetStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return getStudentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStudentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById(params: GetStudentById$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.getStudentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteStudent()` */
  static readonly DeleteStudentPath = '/api/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStudent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent$Response(params: DeleteStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStudent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent(params: DeleteStudent$Params, context?: HttpContext): Observable<void> {
    return this.deleteStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllStudentsByVigyanKendraId()` */
  static readonly GetAllStudentsByVigyanKendraIdPath = '/api/students/vigyan-kendra/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStudentsByVigyanKendraId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudentsByVigyanKendraId$Response(params: GetAllStudentsByVigyanKendraId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponseDto>>> {
    return getAllStudentsByVigyanKendraId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStudentsByVigyanKendraId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudentsByVigyanKendraId(params: GetAllStudentsByVigyanKendraId$Params, context?: HttpContext): Observable<Array<StudentResponseDto>> {
    return this.getAllStudentsByVigyanKendraId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponseDto>>): Array<StudentResponseDto> => r.body)
    );
  }

  /** Path part for operation `generateDummyData()` */
  static readonly GenerateDummyDataPath = '/api/students/generate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateDummyData()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateDummyData$Response(params?: GenerateDummyData$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return generateDummyData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateDummyData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateDummyData(params?: GenerateDummyData$Params, context?: HttpContext): Observable<string> {
    return this.generateDummyData$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
