/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignRollNumber } from '../fn/student-enrollment-api/assign-roll-number';
import { AssignRollNumber$Params } from '../fn/student-enrollment-api/assign-roll-number';
import { createStudent } from '../fn/student-enrollment-api/create-student';
import { CreateStudent$Params } from '../fn/student-enrollment-api/create-student';
import { deleteStudent } from '../fn/student-enrollment-api/delete-student';
import { DeleteStudent$Params } from '../fn/student-enrollment-api/delete-student';
import { DrSheetResponse } from '../models/dr-sheet-response';
import { getAllStudents } from '../fn/student-enrollment-api/get-all-students';
import { GetAllStudents$Params } from '../fn/student-enrollment-api/get-all-students';
import { getAllStudentsByVigyanKendraId } from '../fn/student-enrollment-api/get-all-students-by-vigyan-kendra-id';
import { GetAllStudentsByVigyanKendraId$Params } from '../fn/student-enrollment-api/get-all-students-by-vigyan-kendra-id';
import { getDrSheetData } from '../fn/student-enrollment-api/get-dr-sheet-data';
import { GetDrSheetData$Params } from '../fn/student-enrollment-api/get-dr-sheet-data';
import { getRollNumberAssignmentStatus } from '../fn/student-enrollment-api/get-roll-number-assignment-status';
import { GetRollNumberAssignmentStatus$Params } from '../fn/student-enrollment-api/get-roll-number-assignment-status';
import { getStudentById } from '../fn/student-enrollment-api/get-student-by-id';
import { GetStudentById$Params } from '../fn/student-enrollment-api/get-student-by-id';
import { promoteStudentsToNextSession } from '../fn/student-enrollment-api/promote-students-to-next-session';
import { PromoteStudentsToNextSession$Params } from '../fn/student-enrollment-api/promote-students-to-next-session';
import { RollNumberAssignmentStatus } from '../models/roll-number-assignment-status';
import { StudentResponseDto } from '../models/student-response-dto';
import { updateStudent } from '../fn/student-enrollment-api/update-student';
import { UpdateStudent$Params } from '../fn/student-enrollment-api/update-student';

@Injectable({ providedIn: 'root' })
export class StudentEnrollmentApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllStudents()` */
  static readonly GetAllStudentsPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStudents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents$Response(params?: GetAllStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponseDto>>> {
    return getAllStudents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStudents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents(params?: GetAllStudents$Params, context?: HttpContext): Observable<Array<StudentResponseDto>> {
    return this.getAllStudents$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponseDto>>): Array<StudentResponseDto> => r.body)
    );
  }

  /** Path part for operation `updateStudent()` */
  static readonly UpdateStudentPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent$Response(params: UpdateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return updateStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent(params: UpdateStudent$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.updateStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `createStudent()` */
  static readonly CreateStudentPath = '/api/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStudent$Response(params: CreateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return createStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStudent(params: CreateStudent$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.createStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `promoteStudentsToNextSession()` */
  static readonly PromoteStudentsToNextSessionPath = '/api/students/promote-students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `promoteStudentsToNextSession()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  promoteStudentsToNextSession$Response(params: PromoteStudentsToNextSession$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponseDto>>> {
    return promoteStudentsToNextSession(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `promoteStudentsToNextSession$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  promoteStudentsToNextSession(params: PromoteStudentsToNextSession$Params, context?: HttpContext): Observable<Array<StudentResponseDto>> {
    return this.promoteStudentsToNextSession$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponseDto>>): Array<StudentResponseDto> => r.body)
    );
  }

  /** Path part for operation `getDrSheetData()` */
  static readonly GetDrSheetDataPath = '/api/students/dr-sheet';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDrSheetData()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getDrSheetData$Response(params: GetDrSheetData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DrSheetResponse>>> {
    return getDrSheetData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDrSheetData$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getDrSheetData(params: GetDrSheetData$Params, context?: HttpContext): Observable<Array<DrSheetResponse>> {
    return this.getDrSheetData$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DrSheetResponse>>): Array<DrSheetResponse> => r.body)
    );
  }

  /** Path part for operation `getStudentById()` */
  static readonly GetStudentByIdPath = '/api/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStudentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById$Response(params: GetStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponseDto>> {
    return getStudentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStudentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById(params: GetStudentById$Params, context?: HttpContext): Observable<StudentResponseDto> {
    return this.getStudentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponseDto>): StudentResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteStudent()` */
  static readonly DeleteStudentPath = '/api/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStudent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent$Response(params: DeleteStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStudent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent(params: DeleteStudent$Params, context?: HttpContext): Observable<void> {
    return this.deleteStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllStudentsByVigyanKendraId()` */
  static readonly GetAllStudentsByVigyanKendraIdPath = '/api/students/vigyan-kendra/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStudentsByVigyanKendraId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudentsByVigyanKendraId$Response(params: GetAllStudentsByVigyanKendraId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponseDto>>> {
    return getAllStudentsByVigyanKendraId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStudentsByVigyanKendraId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudentsByVigyanKendraId(params: GetAllStudentsByVigyanKendraId$Params, context?: HttpContext): Observable<Array<StudentResponseDto>> {
    return this.getAllStudentsByVigyanKendraId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponseDto>>): Array<StudentResponseDto> => r.body)
    );
  }

  /** Path part for operation `getRollNumberAssignmentStatus()` */
  static readonly GetRollNumberAssignmentStatusPath = '/api/students/roll-number-assignment-status/{vigyanKendraId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRollNumberAssignmentStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRollNumberAssignmentStatus$Response(params: GetRollNumberAssignmentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<RollNumberAssignmentStatus>> {
    return getRollNumberAssignmentStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRollNumberAssignmentStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRollNumberAssignmentStatus(params: GetRollNumberAssignmentStatus$Params, context?: HttpContext): Observable<RollNumberAssignmentStatus> {
    return this.getRollNumberAssignmentStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<RollNumberAssignmentStatus>): RollNumberAssignmentStatus => r.body)
    );
  }

  /** Path part for operation `assignRollNumber()` */
  static readonly AssignRollNumberPath = '/api/students/assign-roll-number/{vigyanKendraId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignRollNumber()` instead.
   *
   * This method doesn't expect any request body.
   */
  assignRollNumber$Response(params: AssignRollNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<RollNumberAssignmentStatus>> {
    return assignRollNumber(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignRollNumber$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assignRollNumber(params: AssignRollNumber$Params, context?: HttpContext): Observable<RollNumberAssignmentStatus> {
    return this.assignRollNumber$Response(params, context).pipe(
      map((r: StrictHttpResponse<RollNumberAssignmentStatus>): RollNumberAssignmentStatus => r.body)
    );
  }

}
