/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create2 } from '../fn/student-marks-api/create-2';
import { Create2$Params } from '../fn/student-marks-api/create-2';
import { delete2 } from '../fn/student-marks-api/delete-2';
import { Delete2$Params } from '../fn/student-marks-api/delete-2';
import { getAll3 } from '../fn/student-marks-api/get-all-3';
import { GetAll3$Params } from '../fn/student-marks-api/get-all-3';
import { getById3 } from '../fn/student-marks-api/get-by-id-3';
import { GetById3$Params } from '../fn/student-marks-api/get-by-id-3';
import { StudentMarksRequestDto } from '../models/student-marks-request-dto';


/**
 * Endpoints for managing marks awarded to students for specific subjects.
 */
@Injectable({ providedIn: 'root' })
export class StudentMarksApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAll3()` */
  static readonly GetAll3Path = '/api/student-marks';

  /**
   * Get all StudentMarks.
   *
   * Returns a list of all student marks records.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll3$Response(params?: GetAll3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentMarksRequestDto>>> {
    return getAll3(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all StudentMarks.
   *
   * Returns a list of all student marks records.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll3(params?: GetAll3$Params, context?: HttpContext): Observable<Array<StudentMarksRequestDto>> {
    return this.getAll3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentMarksRequestDto>>): Array<StudentMarksRequestDto> => r.body)
    );
  }

  /** Path part for operation `create2()` */
  static readonly Create2Path = '/api/student-marks';

  /**
   * Create a new StudentMarks record.
   *
   * Create a student marks record by specifying student, subject, and marks.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2$Response(params: Create2$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
    return create2(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new StudentMarks record.
   *
   * Create a student marks record by specifying student, subject, and marks.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2(params: Create2$Params, context?: HttpContext): Observable<StudentMarksRequestDto> {
    return this.create2$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentMarksRequestDto>): StudentMarksRequestDto => r.body)
    );
  }

  /** Path part for operation `getById3()` */
  static readonly GetById3Path = '/api/student-marks/{id}';

  /**
   * Get a StudentMarks record by ID.
   *
   * Returns the student marks record for the given ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3$Response(params: GetById3$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
    return getById3(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a StudentMarks record by ID.
   *
   * Returns the student marks record for the given ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3(params: GetById3$Params, context?: HttpContext): Observable<StudentMarksRequestDto> {
    return this.getById3$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentMarksRequestDto>): StudentMarksRequestDto => r.body)
    );
  }

  /** Path part for operation `delete2()` */
  static readonly Delete2Path = '/api/student-marks/{id}';

  /**
   * Delete a StudentMarks record by ID.
   *
   * Deletes the specified student marks record.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete2()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2$Response(params: Delete2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete2(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a StudentMarks record by ID.
   *
   * Deletes the specified student marks record.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2(params: Delete2$Params, context?: HttpContext): Observable<void> {
    return this.delete2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
