/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createMarks } from '../fn/student-marks-api/create-marks';
import { CreateMarks$Params } from '../fn/student-marks-api/create-marks';
import { deleteMarks } from '../fn/student-marks-api/delete-marks';
import { DeleteMarks$Params } from '../fn/student-marks-api/delete-marks';
import { getAllMarks } from '../fn/student-marks-api/get-all-marks';
import { GetAllMarks$Params } from '../fn/student-marks-api/get-all-marks';
import { getMarksById } from '../fn/student-marks-api/get-marks-by-id';
import { GetMarksById$Params } from '../fn/student-marks-api/get-marks-by-id';
import { StudentMarksRequestDto } from '../models/student-marks-request-dto';


/**
 * Endpoints for managing marks awarded to students for specific subjects.
 */
@Injectable({ providedIn: 'root' })
export class StudentMarksApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllMarks()` */
  static readonly GetAllMarksPath = '/api/student-marks';

  /**
   * Get all StudentMarks.
   *
   * Returns a list of all student marks records.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllMarks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMarks$Response(params?: GetAllMarks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentMarksRequestDto>>> {
    return getAllMarks(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all StudentMarks.
   *
   * Returns a list of all student marks records.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllMarks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMarks(params?: GetAllMarks$Params, context?: HttpContext): Observable<Array<StudentMarksRequestDto>> {
    return this.getAllMarks$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentMarksRequestDto>>): Array<StudentMarksRequestDto> => r.body)
    );
  }

  /** Path part for operation `createMarks()` */
  static readonly CreateMarksPath = '/api/student-marks';

  /**
   * Create a new StudentMarks record.
   *
   * Create a student marks record by specifying student, subject, and marks.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMarks()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMarks$Response(params: CreateMarks$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
    return createMarks(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new StudentMarks record.
   *
   * Create a student marks record by specifying student, subject, and marks.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMarks$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMarks(params: CreateMarks$Params, context?: HttpContext): Observable<StudentMarksRequestDto> {
    return this.createMarks$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentMarksRequestDto>): StudentMarksRequestDto => r.body)
    );
  }

  /** Path part for operation `getMarksById()` */
  static readonly GetMarksByIdPath = '/api/student-marks/{id}';

  /**
   * Get a StudentMarks record by ID.
   *
   * Returns the student marks record for the given ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMarksById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMarksById$Response(params: GetMarksById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentMarksRequestDto>> {
    return getMarksById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a StudentMarks record by ID.
   *
   * Returns the student marks record for the given ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMarksById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMarksById(params: GetMarksById$Params, context?: HttpContext): Observable<StudentMarksRequestDto> {
    return this.getMarksById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentMarksRequestDto>): StudentMarksRequestDto => r.body)
    );
  }

  /** Path part for operation `deleteMarks()` */
  static readonly DeleteMarksPath = '/api/student-marks/{id}';

  /**
   * Delete a StudentMarks record by ID.
   *
   * Deletes the specified student marks record.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMarks()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMarks$Response(params: DeleteMarks$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteMarks(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a StudentMarks record by ID.
   *
   * Deletes the specified student marks record.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMarks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMarks(params: DeleteMarks$Params, context?: HttpContext): Observable<void> {
    return this.deleteMarks$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
