/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createClass } from '../fn/student-class-api/create-class';
import { CreateClass$Params } from '../fn/student-class-api/create-class';
import { deleteClass } from '../fn/student-class-api/delete-class';
import { DeleteClass$Params } from '../fn/student-class-api/delete-class';
import { getAllClasses } from '../fn/student-class-api/get-all-classes';
import { GetAllClasses$Params } from '../fn/student-class-api/get-all-classes';
import { getClassById } from '../fn/student-class-api/get-class-by-id';
import { GetClassById$Params } from '../fn/student-class-api/get-class-by-id';
import { StudentClassDetailsResponseDto } from '../models/student-class-details-response-dto';
import { updateClass } from '../fn/student-class-api/update-class';
import { UpdateClass$Params } from '../fn/student-class-api/update-class';

@Injectable({ providedIn: 'root' })
export class StudentClassApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllClasses()` */
  static readonly GetAllClassesPath = '/api/student-class';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllClasses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllClasses$Response(params?: GetAllClasses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentClassDetailsResponseDto>>> {
    return getAllClasses(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllClasses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllClasses(params?: GetAllClasses$Params, context?: HttpContext): Observable<Array<StudentClassDetailsResponseDto>> {
    return this.getAllClasses$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentClassDetailsResponseDto>>): Array<StudentClassDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `updateClass()` */
  static readonly UpdateClassPath = '/api/student-class';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateClass()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateClass$Response(params: UpdateClass$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentClassDetailsResponseDto>> {
    return updateClass(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateClass$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateClass(params: UpdateClass$Params, context?: HttpContext): Observable<StudentClassDetailsResponseDto> {
    return this.updateClass$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentClassDetailsResponseDto>): StudentClassDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `createClass()` */
  static readonly CreateClassPath = '/api/student-class';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createClass()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createClass$Response(params: CreateClass$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentClassDetailsResponseDto>> {
    return createClass(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createClass$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createClass(params: CreateClass$Params, context?: HttpContext): Observable<StudentClassDetailsResponseDto> {
    return this.createClass$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentClassDetailsResponseDto>): StudentClassDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `getClassById()` */
  static readonly GetClassByIdPath = '/api/student-class/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getClassById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getClassById$Response(params: GetClassById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentClassDetailsResponseDto>> {
    return getClassById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getClassById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getClassById(params: GetClassById$Params, context?: HttpContext): Observable<StudentClassDetailsResponseDto> {
    return this.getClassById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentClassDetailsResponseDto>): StudentClassDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteClass()` */
  static readonly DeleteClassPath = '/api/student-class/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteClass()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteClass$Response(params: DeleteClass$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteClass(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteClass$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteClass(params: DeleteClass$Params, context?: HttpContext): Observable<void> {
    return this.deleteClass$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
