/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSubject } from '../fn/subject-details-api/create-subject';
import { CreateSubject$Params } from '../fn/subject-details-api/create-subject';
import { deleteSubject } from '../fn/subject-details-api/delete-subject';
import { DeleteSubject$Params } from '../fn/subject-details-api/delete-subject';
import { getAllSubjects } from '../fn/subject-details-api/get-all-subjects';
import { GetAllSubjects$Params } from '../fn/subject-details-api/get-all-subjects';
import { getSubjectById } from '../fn/subject-details-api/get-subject-by-id';
import { GetSubjectById$Params } from '../fn/subject-details-api/get-subject-by-id';
import { SubjectDetailsResponseDto } from '../models/subject-details-response-dto';
import { updateSubject } from '../fn/subject-details-api/update-subject';
import { UpdateSubject$Params } from '../fn/subject-details-api/update-subject';

@Injectable({ providedIn: 'root' })
export class SubjectDetailsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllSubjects()` */
  static readonly GetAllSubjectsPath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSubjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSubjects$Response(params?: GetAllSubjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubjectDetailsResponseDto>>> {
    return getAllSubjects(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSubjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSubjects(params?: GetAllSubjects$Params, context?: HttpContext): Observable<Array<SubjectDetailsResponseDto>> {
    return this.getAllSubjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SubjectDetailsResponseDto>>): Array<SubjectDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `updateSubject()` */
  static readonly UpdateSubjectPath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSubject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSubject$Response(params: UpdateSubject$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return updateSubject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSubject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSubject(params: UpdateSubject$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.updateSubject$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `createSubject()` */
  static readonly CreateSubjectPath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSubject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSubject$Response(params: CreateSubject$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return createSubject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSubject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSubject(params: CreateSubject$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.createSubject$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `getSubjectById()` */
  static readonly GetSubjectByIdPath = '/api/subject-details/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubjectById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubjectById$Response(params: GetSubjectById$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return getSubjectById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubjectById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubjectById(params: GetSubjectById$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.getSubjectById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteSubject()` */
  static readonly DeleteSubjectPath = '/api/subject-details/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSubject()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSubject$Response(params: DeleteSubject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSubject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSubject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSubject(params: DeleteSubject$Params, context?: HttpContext): Observable<void> {
    return this.deleteSubject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
