/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/subject-details-api/create';
import { Create$Params } from '../fn/subject-details-api/create';
import { delete1 } from '../fn/subject-details-api/delete-1';
import { Delete1$Params } from '../fn/subject-details-api/delete-1';
import { getAll } from '../fn/subject-details-api/get-all';
import { GetAll$Params } from '../fn/subject-details-api/get-all';
import { getById2 } from '../fn/subject-details-api/get-by-id-2';
import { GetById2$Params } from '../fn/subject-details-api/get-by-id-2';
import { SubjectDetailsResponseDto } from '../models/subject-details-response-dto';
import { update } from '../fn/subject-details-api/update';
import { Update$Params } from '../fn/subject-details-api/update';

@Injectable({ providedIn: 'root' })
export class SubjectDetailsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAll()` */
  static readonly GetAllPath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll$Response(params?: GetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubjectDetailsResponseDto>>> {
    return getAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll(params?: GetAll$Params, context?: HttpContext): Observable<Array<SubjectDetailsResponseDto>> {
    return this.getAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SubjectDetailsResponseDto>>): Array<SubjectDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/subject-details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `getById2()` */
  static readonly GetById2Path = '/api/subject-details/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2$Response(params: GetById2$Params, context?: HttpContext): Observable<StrictHttpResponse<SubjectDetailsResponseDto>> {
    return getById2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2(params: GetById2$Params, context?: HttpContext): Observable<SubjectDetailsResponseDto> {
    return this.getById2$Response(params, context).pipe(
      map((r: StrictHttpResponse<SubjectDetailsResponseDto>): SubjectDetailsResponseDto => r.body)
    );
  }

  /** Path part for operation `delete1()` */
  static readonly Delete1Path = '/api/subject-details/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete1()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1$Response(params: Delete1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1(params: Delete1$Params, context?: HttpContext): Observable<void> {
    return this.delete1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
