/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAll2 } from '../fn/vigyankendra-deatils-api/get-all-2';
import { GetAll2$Params } from '../fn/vigyankendra-deatils-api/get-all-2';
import { getByCode } from '../fn/vigyankendra-deatils-api/get-by-code';
import { GetByCode$Params } from '../fn/vigyankendra-deatils-api/get-by-code';
import { getById1 } from '../fn/vigyankendra-deatils-api/get-by-id-1';
import { GetById1$Params } from '../fn/vigyankendra-deatils-api/get-by-id-1';
import { getSchoolsByCode } from '../fn/vigyankendra-deatils-api/get-schools-by-code';
import { GetSchoolsByCode$Params } from '../fn/vigyankendra-deatils-api/get-schools-by-code';
import { getUsersById } from '../fn/vigyankendra-deatils-api/get-users-by-id';
import { GetUsersById$Params } from '../fn/vigyankendra-deatils-api/get-users-by-id';
import { getVigyanKendraDetails } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-details';
import { GetVigyanKendraDetails$Params } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-details';
import { SchoolDetailsResponseDto } from '../models/school-details-response-dto';
import { UserDetails } from '../models/user-details';
import { VigyanKendraDetailsRequestDto } from '../models/vigyan-kendra-details-request-dto';


/**
 * Endpoints for managing Vigyan kendra.
 */
@Injectable({ providedIn: 'root' })
export class VigyankendraDeatilsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAll2()` */
  static readonly GetAll2Path = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2$Response(params?: GetAll2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>> {
    return getAll2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2(params?: GetAll2$Params, context?: HttpContext): Observable<Array<VigyanKendraDetailsRequestDto>> {
    return this.getAll2$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>): Array<VigyanKendraDetailsRequestDto> => r.body)
    );
  }

  /** Path part for operation `getVigyanKendraDetails()` */
  static readonly GetVigyanKendraDetailsPath = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVigyanKendraDetails()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getVigyanKendraDetails$Response(params: GetVigyanKendraDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return getVigyanKendraDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVigyanKendraDetails$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getVigyanKendraDetails(params: GetVigyanKendraDetails$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.getVigyanKendraDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `getById1()` */
  static readonly GetById1Path = '/api/vigyan-kendra/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1$Response(params: GetById1$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return getById1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1(params: GetById1$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.getById1$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `getUsersById()` */
  static readonly GetUsersByIdPath = '/api/vigyan-kendra/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersById$Response(params: GetUsersById$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDetails>>> {
    return getUsersById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersById(params: GetUsersById$Params, context?: HttpContext): Observable<Array<UserDetails>> {
    return this.getUsersById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserDetails>>): Array<UserDetails> => r.body)
    );
  }

  /** Path part for operation `getSchoolsByCode()` */
  static readonly GetSchoolsByCodePath = '/api/vigyan-kendra/schools/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSchoolsByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolsByCode$Response(params: GetSchoolsByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolDetailsResponseDto>>> {
    return getSchoolsByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSchoolsByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolsByCode(params: GetSchoolsByCode$Params, context?: HttpContext): Observable<Array<SchoolDetailsResponseDto>> {
    return this.getSchoolsByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SchoolDetailsResponseDto>>): Array<SchoolDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `getByCode()` */
  static readonly GetByCodePath = '/api/vigyan-kendra/code/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCode$Response(params: GetByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return getByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCode(params: GetByCode$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.getByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

}
