/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createVigyanKendraDetails } from '../fn/vigyankendra-deatils-api/create-vigyan-kendra-details';
import { CreateVigyanKendraDetails$Params } from '../fn/vigyankendra-deatils-api/create-vigyan-kendra-details';
import { deleteVigyanKendraById } from '../fn/vigyankendra-deatils-api/delete-vigyan-kendra-by-id';
import { DeleteVigyanKendraById$Params } from '../fn/vigyankendra-deatils-api/delete-vigyan-kendra-by-id';
import { getAllVigyanKendras } from '../fn/vigyankendra-deatils-api/get-all-vigyan-kendras';
import { GetAllVigyanKendras$Params } from '../fn/vigyankendra-deatils-api/get-all-vigyan-kendras';
import { getSchoolsByVigyanKendraId } from '../fn/vigyankendra-deatils-api/get-schools-by-vigyan-kendra-id';
import { GetSchoolsByVigyanKendraId$Params } from '../fn/vigyankendra-deatils-api/get-schools-by-vigyan-kendra-id';
import { getUsersByVigyanKendraId } from '../fn/vigyankendra-deatils-api/get-users-by-vigyan-kendra-id';
import { GetUsersByVigyanKendraId$Params } from '../fn/vigyankendra-deatils-api/get-users-by-vigyan-kendra-id';
import { getVigyanKendraByCode } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-by-code';
import { GetVigyanKendraByCode$Params } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-by-code';
import { getVigyanKendraById } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-by-id';
import { GetVigyanKendraById$Params } from '../fn/vigyankendra-deatils-api/get-vigyan-kendra-by-id';
import { SchoolDetailsResponseDto } from '../models/school-details-response-dto';
import { updateVigyanKendraDetails } from '../fn/vigyankendra-deatils-api/update-vigyan-kendra-details';
import { UpdateVigyanKendraDetails$Params } from '../fn/vigyankendra-deatils-api/update-vigyan-kendra-details';
import { UserDetails } from '../models/user-details';
import { VigyanKendraDetailsRequestDto } from '../models/vigyan-kendra-details-request-dto';


/**
 * Endpoints for managing Vigyan kendra.
 */
@Injectable({ providedIn: 'root' })
export class VigyankendraDeatilsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllVigyanKendras()` */
  static readonly GetAllVigyanKendrasPath = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllVigyanKendras()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVigyanKendras$Response(params?: GetAllVigyanKendras$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>> {
    return getAllVigyanKendras(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllVigyanKendras$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVigyanKendras(params?: GetAllVigyanKendras$Params, context?: HttpContext): Observable<Array<VigyanKendraDetailsRequestDto>> {
    return this.getAllVigyanKendras$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VigyanKendraDetailsRequestDto>>): Array<VigyanKendraDetailsRequestDto> => r.body)
    );
  }

  /** Path part for operation `updateVigyanKendraDetails()` */
  static readonly UpdateVigyanKendraDetailsPath = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateVigyanKendraDetails()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVigyanKendraDetails$Response(params: UpdateVigyanKendraDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return updateVigyanKendraDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateVigyanKendraDetails$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVigyanKendraDetails(params: UpdateVigyanKendraDetails$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.updateVigyanKendraDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `createVigyanKendraDetails()` */
  static readonly CreateVigyanKendraDetailsPath = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createVigyanKendraDetails()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVigyanKendraDetails$Response(params: CreateVigyanKendraDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return createVigyanKendraDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createVigyanKendraDetails$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVigyanKendraDetails(params: CreateVigyanKendraDetails$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.createVigyanKendraDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `deleteVigyanKendraById()` */
  static readonly DeleteVigyanKendraByIdPath = '/api/vigyan-kendra';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteVigyanKendraById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteVigyanKendraById$Response(params: DeleteVigyanKendraById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteVigyanKendraById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteVigyanKendraById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteVigyanKendraById(params: DeleteVigyanKendraById$Params, context?: HttpContext): Observable<void> {
    return this.deleteVigyanKendraById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getVigyanKendraById()` */
  static readonly GetVigyanKendraByIdPath = '/api/vigyan-kendra/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVigyanKendraById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVigyanKendraById$Response(params: GetVigyanKendraById$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return getVigyanKendraById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVigyanKendraById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVigyanKendraById(params: GetVigyanKendraById$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.getVigyanKendraById$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

  /** Path part for operation `getUsersByVigyanKendraId()` */
  static readonly GetUsersByVigyanKendraIdPath = '/api/vigyan-kendra/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersByVigyanKendraId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByVigyanKendraId$Response(params: GetUsersByVigyanKendraId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDetails>>> {
    return getUsersByVigyanKendraId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersByVigyanKendraId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByVigyanKendraId(params: GetUsersByVigyanKendraId$Params, context?: HttpContext): Observable<Array<UserDetails>> {
    return this.getUsersByVigyanKendraId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserDetails>>): Array<UserDetails> => r.body)
    );
  }

  /** Path part for operation `getSchoolsByVigyanKendraId()` */
  static readonly GetSchoolsByVigyanKendraIdPath = '/api/vigyan-kendra/schools/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSchoolsByVigyanKendraId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolsByVigyanKendraId$Response(params: GetSchoolsByVigyanKendraId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolDetailsResponseDto>>> {
    return getSchoolsByVigyanKendraId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSchoolsByVigyanKendraId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSchoolsByVigyanKendraId(params: GetSchoolsByVigyanKendraId$Params, context?: HttpContext): Observable<Array<SchoolDetailsResponseDto>> {
    return this.getSchoolsByVigyanKendraId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SchoolDetailsResponseDto>>): Array<SchoolDetailsResponseDto> => r.body)
    );
  }

  /** Path part for operation `getVigyanKendraByCode()` */
  static readonly GetVigyanKendraByCodePath = '/api/vigyan-kendra/code/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVigyanKendraByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVigyanKendraByCode$Response(params: GetVigyanKendraByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<VigyanKendraDetailsRequestDto>> {
    return getVigyanKendraByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVigyanKendraByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVigyanKendraByCode(params: GetVigyanKendraByCode$Params, context?: HttpContext): Observable<VigyanKendraDetailsRequestDto> {
    return this.getVigyanKendraByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<VigyanKendraDetailsRequestDto>): VigyanKendraDetailsRequestDto => r.body)
    );
  }

}
