/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { VigyankendraDeatilsApiService } from './services/vigyankendra-deatils-api.service';
import { UserManagementApiService } from './services/user-management-api.service';
import { SubjectDetailsApiService } from './services/subject-details-api.service';
import { StudentEnrollmentApiService } from './services/student-enrollment-api.service';
import { StudentClassApiService } from './services/student-class-api.service';
import { SchoolDetailsApiService } from './services/school-details-api.service';
import { ExaminationCentreDetailsApiService } from './services/examination-centre-details-api.service';
import { StudentMarksApiService } from './services/student-marks-api.service';
import { AuthApiService } from './services/auth-api.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    VigyankendraDeatilsApiService,
    UserManagementApiService,
    SubjectDetailsApiService,
    StudentEnrollmentApiService,
    StudentClassApiService,
    SchoolDetailsApiService,
    ExaminationCentreDetailsApiService,
    StudentMarksApiService,
    AuthApiService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
