/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { VigyankendraDeatilsApiService } from './services/vigyankendra-deatils-api.service';
export { UserManagementApiService } from './services/user-management-api.service';
export { SubjectDetailsApiService } from './services/subject-details-api.service';
export { StudentEnrollmentApiService } from './services/student-enrollment-api.service';
export { StudentClassApiService } from './services/student-class-api.service';
export { SchoolDetailsApiService } from './services/school-details-api.service';
export { ExaminationCentreDetailsApiService } from './services/examination-centre-details-api.service';
export { StudentMarksApiService } from './services/student-marks-api.service';
export { AuthApiService } from './services/auth-api.service';
