/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DrSheetRequest {
  classId?: number;
  examCenterId?: number;
  vigyanKendraId?: number;
}
