/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollmentReportingResponse {
  enrollmentYear?: number;
  id?: number;
  reportDate?: string;
  reportKey?: string;
  reportName?: string;
  status?: string;
  vigyanKendraCode?: string;
  vigyanKendraName?: string;
}
