/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollmentSession {
  active?: boolean;
  enrollmentFreezed?: boolean;
  id?: number;
  modificationFreezed?: boolean;
  name?: string;
  year?: number;
}
