/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollmentReportingRequest {
  enrollmentSessionId?: number;
  vigyanKendraId?: number;
}
