/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExaminationCentreDetailsRequestDto {
  id?: number;
  name?: string;
  schoolDetailsId?: number;
  vigyanKendraId?: number;
}
