/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExaminationCentreDetailsRequestDto {
  enrollmentId?: number;
  enrollmentYear?: number;
  id?: number;
  name?: string;
  schoolDetailsId?: number;
  schoolName?: string;
  schoolNames?: Array<string>;
  vigyanKendraCode?: string;
  vigyanKendraId?: number;
  vigyanKendraName?: string;
}
