/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnrollmentSession } from '../models/enrollment-session';
import { SchoolDetails } from '../models/school-details';
import { VigyanKendraDetails } from '../models/vigyan-kendra-details';
export interface ExaminationCentreDetails {
  createdBy?: string;
  createdDate?: string;
  details?: SchoolDetails;
  enrollmentSession?: EnrollmentSession;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  schools?: Array<SchoolDetails>;
  vigyanKendraDetails?: VigyanKendraDetails;
}
