/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JwtResponse {
  adminUser?: boolean;
  id?: number;
  jwt?: string;
  roles?: Array<string>;
  schoolUser?: boolean;
  userName?: string;
  vigyanKendraCode?: string;
  vigyanKendraId?: number;
  vigyanKendraName?: string;
  vigyanKendraUser?: boolean;
}
