/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: 'ROLE_ADMIN' | 'ROLE_VIGYANKENDRA' | 'ROLE_SCHOOL' | 'ROLE_NONE';
}
