/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExaminationCentreDetails } from '../models/examination-centre-details';
import { VigyanKendraDetails } from '../models/vigyan-kendra-details';
export interface SchoolDetails {
  createdBy?: string;
  createdDate?: string;
  examinationCentre?: ExaminationCentreDetails;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  vigyanKendraDetails?: VigyanKendraDetails;
}
