/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnrollmentSession } from '../models/enrollment-session';
import { ExaminationCentreDetails } from '../models/examination-centre-details';
import { Student } from '../models/student';
import { VigyanKendraDetails } from '../models/vigyan-kendra-details';
export interface SchoolDetails {
  createdBy?: string;
  createdDate?: string;
  enrollmentSession?: EnrollmentSession;
  examinationCentre?: ExaminationCentreDetails;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  students?: Array<Student>;
  vigyanKendraDetails?: VigyanKendraDetails;
}
