/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchoolDetailsResponseDto {
  examinationCentreId?: number;
  examinationCentreName?: string;
  id?: number;
  name?: string;
  vigyanKendraId?: number;
  vigyanKendraName?: string;
}
