/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchoolAssignDeAssignRequest {
  examinationCentreId?: number;
  schoolIds?: Array<number>;
}
