/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchoolDetailsRequestDto {
  examCentreId?: number;
  examCentreName?: string;
  id?: number;
  name?: string;
  vigyanKendraId?: number;
  vigyanKendraName?: string;
}
