/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignupRequest {
  admin?: boolean;
  email?: string;
  password?: string;
  roles?: Array<string>;
  userId?: number;
  userName?: string;
  vigyanKendraId?: number;
}
