/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentRequestDto {
  id?: number;
  name?: string;
  schoolId?: number;
  sex?: string;
  studentClassId?: number;
  vigyanKendraId?: number;
}
