/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentResponseDto {
  classId?: number;
  className?: string;
  enrollmentId?: number;
  enrollmentYear?: number;
  examinationCentreId?: number;
  examinationCentreName?: string;
  id?: number;
  name?: string;
  number?: string;
  roll?: string;
  schoolId?: number;
  schoolName?: string;
  sex?: string;
  vigyanKendraId?: number;
  vigyanKendraName?: string;
}
