/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentClassRequestDto {
  id?: number;
  name?: string;
  subjectIds?: Array<number>;
}
