/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SchoolDetails } from '../models/school-details';
import { StudentClass } from '../models/student-class';
import { VigyanKendraDetails } from '../models/vigyan-kendra-details';
export interface Student {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  number?: string;
  roll?: string;
  schoolDetails?: SchoolDetails;
  sex: string;
  studentClass?: StudentClass;
  vigyanKendraDetails?: VigyanKendraDetails;
}
