/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentMarksRequestDto {
  id?: number;
  marks: number;
  maximumMarks: number;
  studentId: number;
  subjectId: number;
}
