/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubjectDetails } from '../models/subject-details';
export interface StudentClass {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  subjects?: Array<SubjectDetails>;
}
