/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentClass } from '../models/student-class';
export interface SubjectDetails {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  name?: string;
  studentClasses?: Array<StudentClass>;
}
