/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
import { VigyanKendraDetails } from '../models/vigyan-kendra-details';
export interface UserDetails {
  createdBy?: string;
  createdDate?: string;
  email?: string;
  id?: number;
  modifiedBy?: string;
  modifiedDate?: string;
  roles?: Array<Role>;
  userName?: string;
  vigyanKendraDetails?: VigyanKendraDetails;
}
