/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExaminationCentreDetailsRequestDto } from '../../models/examination-centre-details-request-dto';
import { SchoolAssignDeAssignRequest } from '../../models/school-assign-de-assign-request';

export interface AssignSchool$Params {
      body: SchoolAssignDeAssignRequest
}

export function assignSchool(http: HttpClient, rootUrl: string, params: AssignSchool$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
  const rb = new RequestBuilder(rootUrl, assignSchool.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExaminationCentreDetailsRequestDto>;
    })
  );
}

assignSchool.PATH = '/api/examination-centres/assign';
