/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExaminationCentreDetailsRequestDto } from '../../models/examination-centre-details-request-dto';

export interface GetExamCenterById$Params {
  id: number;
}

export function getExamCenterById(http: HttpClient, rootUrl: string, params: GetExamCenterById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExaminationCentreDetailsRequestDto>> {
  const rb = new RequestBuilder(rootUrl, getExamCenterById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExaminationCentreDetailsRequestDto>;
    })
  );
}

getExamCenterById.PATH = '/api/examination-centres/{id}';
