/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExaminationCentreDetailsRequestDto } from '../../models/examination-centre-details-request-dto';

export interface GetAllExamCenters$Params {
}

export function getAllExamCenters(http: HttpClient, rootUrl: string, params?: GetAllExamCenters$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllExamCenters.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExaminationCentreDetailsRequestDto>>;
    })
  );
}

getAllExamCenters.PATH = '/api/examination-centres';
