/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SchoolDetailsRequestDto } from '../../models/school-details-request-dto';

export interface GetAllSchools$Params {
}

export function getAllSchools(http: HttpClient, rootUrl: string, params?: GetAllSchools$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolDetailsRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllSchools.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SchoolDetailsRequestDto>>;
    })
  );
}

getAllSchools.PATH = '/api/schools';
