/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollmentSession } from '../../models/enrollment-session';

export interface CreateEnrollmentSession$Params {
      body: EnrollmentSession
}

export function createEnrollmentSession(http: HttpClient, rootUrl: string, params: CreateEnrollmentSession$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
  const rb = new RequestBuilder(rootUrl, createEnrollmentSession.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnrollmentSession>;
    })
  );
}

createEnrollmentSession.PATH = '/api/enrollment-session';
