/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollmentSession } from '../../models/enrollment-session';

export interface SetModificationUnFreezed$Params {
  id: number;
}

export function setModificationUnFreezed(http: HttpClient, rootUrl: string, params: SetModificationUnFreezed$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollmentSession>> {
  const rb = new RequestBuilder(rootUrl, setModificationUnFreezed.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnrollmentSession>;
    })
  );
}

setModificationUnFreezed.PATH = '/api/enrollment-session/{id}/modification-unfreeze';
